version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat_repository"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/chat_repository_interface"
    schedule:
      interval: "weekly"
