version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat_firebase"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat_interface"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_chat_view"
    schedule:
      interval: "weekly"
