# SPDX-FileCopyrightText: 2022 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_chat_view
description: A standard flutter package.
version: 3.0.1

publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  emoji_picker_flutter: ^2.2.0
  google_fonts: ^6.2.1
  flutter_chat_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_chat
      path: packages/flutter_chat_interface
      ref: 3.0.1
  cached_network_image: ^3.2.2
  flutter_image_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_image_picker
      ref: 3.0.0
  flutter_profile:
    git:
      ref: 1.3.0
      url: https://github.com/Iconica-Development/flutter_profile

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
