name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_chat:
    path: ../
  flutter_chat_firebase:
    path: ../../flutter_chat_firebase
dependency_overrides:
  flutter_chat:
    path: ../../flutter_chat
  flutter_chat_interface:
    path: ../../flutter_chat_interface
  flutter_chat_local:
    path: ../../flutter_chat_local
  flutter_chat_view:
    path: ../../flutter_chat_view

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
  uses-material-design: true
