name: flutter_community_chat_firebase
description: A new Flutter package project.
version: 0.3.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_auth: ^4.1.2
  uuid: ^3.0.6
  flutter:
    sdk: flutter
  flutter_community_chat_interface: 
    git: 
       url: https://github.com/Iconica-Development/flutter_community_chat.git
       path: packages/flutter_community_chat_interface
       ref: feature/group-chats

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

