name: firebase_chat_repository
description: "Firebase repository implementation for the chat domain repository interface"
version: 5.0.0
homepage: "https://github.com/Iconica-Development"

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  chat_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0

  firebase_storage: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
