# SPDX-FileCopyrightText: 2022 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_community_chat_view
description: A standard flutter package.
version: 0.5.0

publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  flutter_community_chat_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_community_chat
      path: packages/flutter_community_chat_interface
      ref: 0.5.0
  cached_network_image: ^3.2.2
  flutter_image_picker:
    git:
      url: https://github.com/Iconica-Development/flutter_image_picker
      ref: 1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
