name: flutter_chat
description: "User story of the chat domain for quick integration into flutter apps"
version: 5.0.0
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.2
  intl: any
  flutter_hooks: ^0.20.5

  flutter_accessibility:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^0.0.2
  flutter_image_picker:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^4.0.0
  flutter_profile:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^1.6.0
  chat_repository_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
