# SPDX-FileCopyrightText: 2022 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_chat
description: A new Flutter package project.
version: 1.1.0

publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: any
  flutter_chat_view:
    git:
      url: https://github.com/Iconica-Development/flutter_chat
      path: packages/flutter_chat_view
      ref: 1.1.0
  flutter_chat_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_chat
      path: packages/flutter_chat_interface
      ref: 1.1.0
  flutter_chat_local:
    git:
      url: https://github.com/Iconica-Development/flutter_chat
      path: packages/flutter_chat_local
      ref: 1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
