# SPDX-FileCopyrightText: 2022 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_chat_firebase
description: A new Flutter package project.
version: 3.0.1

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_auth: ^4.1.2
  uuid: ^4.0.0
  flutter_chat_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub
    version: ^3.1.0

dev_dependencies:
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0

flutter:
