name: flutter_community_chat
description: A new Flutter package project.
version: 0.3.3

publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_community_chat_view:
    git: 
       url: https://github.com/Iconica-Development/flutter_community_chat
       path: packages/flutter_community_chat_view
       ref: 0.3.3
  flutter_community_chat_interface:
    git: 
       url: https://github.com/Iconica-Development/flutter_community_chat
       path: packages/flutter_community_chat_interface
       ref: 0.3.3

dev_dependencies:
  flutter_lints: ^2.0.0


flutter:

