name: flutter_chat_local
description: "A new Flutter package project."
version: 3.1.0
publish_to: none

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_interface:
    git:
      url: https://github.com/Iconica-Development/flutter_chat
      path: packages/flutter_chat_interface
      ref: 3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
flutter:
