name: chat_repository_interface
description: "The interface for a chat repository"
version: 5.1.0
homepage: "https://github.com/Iconica-Development"

publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  rxdart: any
  collection: any

dev_dependencies:
  test: ^1.24.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 7.0.0
